#!/bin/bash

# set to 1 for motelab testbeds
#export CFLAGS="$CFLAGS -DTINYOS_SERIAL_FRAMES=1"

# set COOJA to 1 for simulating Glossy in Cooja
export CFLAGS="$CFLAGS -DCOOJA=1"
export CFLAGS="$CFLAGS -DDISABLE_ETIMER=1"

export CFLAGS="$CFLAGS -DCRYSTAL_CONF_PERIOD=1"
export CFLAGS="$CFLAGS -DCRYSTAL_LOGGING=1"
export CFLAGS="$CFLAGS -DDISABLE_UART=0"
export CFLAGS="$CFLAGS -DCRYSTAL_SINK_ID=1" 
export CFLAGS="$CFLAGS -DSTART_EPOCH=1" 
export CFLAGS="$CFLAGS -DN_FULL_EPOCHS=10"

export CFLAGS="$CFLAGS -DTX_POWER=31 -DRF_CHANNEL=26 -DCONCURRENT_TXS=5 -DNUM_ACTIVE_EPOCHS=1 -DN_TX_S=5 -DN_TX_T=5 -DN_TX_A=5 -DDUR_S_MS=12 -DDUR_T_MS=10 -DDUR_A_MS=12 -DCRYSTAL_LONGSKIP=0 -DCRYSTAL_SYNC_ACKS=1"
export CFLAGS="$CFLAGS -DCRYSTAL_SINK_MAX_EMPTY_TS=2 -DCRYSTAL_MAX_SILENT_TAS=2 -DCRYSTAL_MAX_MISSING_ACKS=4 -DCRYSTAL_SINK_MAX_NOISY_TS=6"
export CFLAGS="$CFLAGS -DCRYSTAL_USE_DYNAMIC_NEMPTY=0"
export CFLAGS="$CFLAGS -DCCA_THRESHOLD=-32 -DCCA_COUNTER_THRESHOLD=80"
export CFLAGS="$CFLAGS -DCRYSTAL_PAYLOAD_LENGTH=2"
#export CFLAGS="$CFLAGS -DSHORT_LOGS=1"

#export CFLAGS="$CFLAGS -DCHHOP_MAPPING=CHMAP_nohop"
export CFLAGS="$CFLAGS -DCHHOP_MAPPING=CHMAP_nomap"
#export CFLAGS="$CFLAGS -DBOOT_CHOPPING=BOOT_nohop"
export CFLAGS="$CFLAGS -DBOOT_CHOPPING=BOOT_hop3"

export CFLAGS="$CFLAGS -DCRYSTAL_START_DELAY_NONSINK=0 -DCRYSTAL_START_DELAY_SINK=0"

cp sndtbl_cooja.c sndtbl.c

make clean
rm crystal.sky

make 
