#define TX_POWER 31
#define CRYSTAL_CONF_DEF_CHANNEL 26

#define CRYSTAL_CONF_N_FULL_EPOCHS 5
#define CRYSTAL_CONF_CHHOP_MAPPING CHMAP_nomap
#define CRYSTAL_CONF_BSTRAP_CHHOPPING BSTRAP_hop3


//#define CRYSTAL_CONF_LOGLEVEL CRYSTAL_LOGS_ALL
//#define CRYSTAL_CONF_LOGLEVEL CRYSTAL_LOGS_EPOCH_STATS
#define CRYSTAL_CONF_LOGLEVEL CRYSTAL_LOGS_NONE

#define CRYSTAL_CONF_TIME_FOR_APP (RTIMER_SECOND/10) // for app logs
//#define CRYSTAL_CONF_TIME_FOR_APP (RTIMER_SECOND/3) // for ALL logs
